### ISSUE TITLE
Can't build on fresh Ubuntu 12.04.5

### ISSUE THREAD

**Issue by bloo** [facebook/bistro#2]
Building from the docker image for Ubuntu 12.04.5 fails when attempting to use cmake as the build script installs a version that's too low:

```
+ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
update-alternatives: using /usr/bin/gcc-4.8 to provide /usr/bin/gcc (gcc) in auto mode.
+ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
update-alternatives: using /usr/bin/g++-4.8 to provide /usr/bin/g++ (g++) in auto mode.
+ CMAKE_NAME=cmake-2.8.12.1
+ GFLAGS_VER=2.1.1
+ GLOG_NAME=glog-0.3.3
+ pushd .
+ git clone https://github.com/google/double-conversion
/bistro/bistro/build/deps/fbthrift/thrift/build/deps/folly/folly/build/deps /bistro/bistro/build/deps/fbthrift/thrift/build/deps/folly/folly/build/deps
Cloning into 'double-conversion'...
+ cd double-conversion
+ cmake -DBUILD_SHARED_LIBS=ON .
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 2.8.12 or higher is required.  You are running version 2.8.7
```

I attempted to build using 14.04.4 and the build script gets further and fails trying to fetch from a PPA:

`W: Failed to fetch http://ppa.launchpad.net/boost-latest/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found`

What am I missing here?

**Comment by bloo** [comment]
@snarkmaster et al, is this project dead?

**Comment by snarkmaster** [comment]
@bloo -- hey, no, it's not dead, I'm actually preparing a bunch of other pieces for release, at which point the build will be ready. Long story short -- the summer's early release simply accompanied a paper publication, and was never meant to be the "here, use this". Unfortunately, I then had to take a personal hiatus, and only recently resumed work on the full release.

Thanks for the report!

Regarding your specific question, what happened was that I failed to pin the `double-conversion` git hash, and their trunk moved on to a more modern CMake. The older CMake used to work fine.

If you `git checkout c3e0c97328653d23630db7a633ec7b96a1f61f50` right after cloning `double-conversion`, the build on 12.04 should work again. I'd push a fix, but I think it's much more important that I get the tons of unreleased code I have up here, and accompanying docs.

Stay tuned, and consider joining: https://www.facebook.com/groups/bistro.scheduler/

Also, feel free to message me about the use-case you have in mind (or post it here). I'm happy to discuss.

**Comment by snarkmaster** [comment]
@bloo -- if you want to check out Bistro again, we have over 140 fresh commits from the last 1.5-2 years bringing some pretty awesome goodies, as well as a new Docker-based continuous-integration build setup that supports `debian:8.6`, `ubuntu:14.04` and `ubuntu:16.04`. Please file any issues you find, we'll get it fixed right away.
