### ISSUE TITLE
Docker build failed with permissions denied error on step 119

### ISSUE THREAD

**Issue by pspsachan** [facebook/bistro#25]
Hello,

I tried building bistro using docker image and i am facing this issue .

Command :
os_image=ubuntu:16.04   gcc_version=5   make_parallelism=2   travis_cache_dir=~/travis_ccache     ./../build/fbcode_builder/travis_docker_build.sh

Error:
Step 119/126 : RUN PATH="$PATH:"'/home/install'/bin TEMPLATES_PATH='/home/install'/include/thrift/templates ./cmake/run-cmake.sh Debug -DCMAKE_INSTALL_PREFIX='/home/install'
 ---> Running in e731295f3654
/bin/bash: ./cmake/run-cmake.sh: Permission denied
The command '/bin/bash -c PATH="$PATH:"'/home/install'/bin TEMPLATES_PATH='/home/install'/include/thrift/templates ./cmake/run-cmake.sh Debug -DCMAKE_INSTALL_PREFIX='/home/install'' returned a non-zero code: 126
+ build_exit_code=126
+ echo 'Build failed with code 126, trying to save ccache'
Build failed with code 126, trying to save ccache

This file seems to have all the permissions. Don't know whats going wrong.
rwxrwxrwx 1 psachan psachan 3K Jan 11 11:58 ./cmake/run-cmake.sh*

Any help is appreciated. 
Thanks

**Comment by snarkmaster** [comment]
Thanks for writing. I have not been able to reproduce this issue in an Ubuntu 14.04 VM with Docker 1.12.5, as well as some other 16.04 VMs. Also, Bistro's Travis builds pass most of the time these days.

So, something has to be different about your environment. Let me ask some questions:

 - Does this still reproduce for you?
 - Are you working with a clean checkout?
 - I'm pretty surprised that your `run-cmake.sh` is world-writable. Did you change that?
 - Which OS are you on? Docker version?
 - What filesystem is your git checkout on?

**Comment by snarkmaster** [comment]
Please reopen with more details if this is still important to you.
