### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by avnerbarr** [facebook/bistro#27]
I've tried running `/home/avner/bistro/bistro/cmake/run-cmake.sh` 

I get an error about "thrift1" . I went ahead and installed thrift , but thrift1 doesn't exist.

Are there some instructions how to install this?

**Comment by snarkmaster** [comment]
You can generate the instructions for installing all the dependencies in the form of a Dockerfile by using `make_docker_context.py`, check out the README in this subdirectory:

https://github.com/facebook/bistro/tree/master/build/fbcode_builder

**Comment by snarkmaster** [comment]
By the way, I would use a commit that has a green Travis build, e.g. https://github.com/facebook/bistro/commit/faabd53918f101f9e59686eb18b657c4c44311cf

The context is that Bistro's dependencies often break the build, even though the core code is stable. You are not losing anything by using a slightly older commit.
