### ISSUE TITLE
Cannot build Bistro on Debian 9

### ISSUE THREAD

**Issue by arghasen** [facebook/bistro#28]
When i run run_cmake.sh I get the following error.
admin@instance-bistro-test:/bistro/bistro/bistro/cmake$ ./run-cmake.sh Debug
/bistro/bistro/bistro/cmake/deps /bistro/bistro/bistro/cmake
/bistro/bistro/bistro/cmake
Generating Thrift Files
/bistro /bistro/bistro/bistro
!!! Unrecognized option: /bistro/bistro/bistro/cmake/../../..
Usage: thrift [options] file

**Comment by arghasen** [comment]
I was not passing the TEMPLATES_PATH

**Comment by arghasen** [comment]
@snarkmaster I had not used docker earlier so it was not a path I tried. I am more comfortable with the standard make /cmake based toolchain.

**Comment by snarkmaster** [comment]
Got it. For this project, Docker is just a way of getting all the right dependencies in a reliable, automated way. Outside of a controlled container, it's a lot more work to write code that will correctly set up all the dependencies for Bistro. The Docker method still uses automake & cmake to build the various projects.
