### ISSUE TITLE
custom synonyms list not saved

### ISSUE THREAD

**Issue by pc-emory** [facebook/bistro#29]
Hi,

I created  custom synonyms list (Tools > create custom synonyms), gave a name, input about 200 positions and clicked on 'save'. However, when trying to filter ('search this file') the name doesn't autocomplete, and going back to Tools > create custom synonyms, you see that the synonym that was just created/saved, is not there. 

thanks,

Pankaj

**Comment by pc-emory** [comment]
So, after a few attempts, it did save.....maybe I reached my account quota and it couldn't save? But might still be worth looking into....

**Comment by snarkmaster** [comment]
Hi, I think you must have meant to open an issue for a different project! Bistro is a distributed job scheduler, it doesn't have a Tools menu or synonyms.
