### ISSUE TITLE
Python 2 syntax error in scratch_test.py

### ISSUE THREAD

**Issue by cclauss** [facebook/bistro#35]
$ [__python2 -c "C:\users"__](https://github.com/facebook/bistro/blob/master/build/fbcode_builder/getdeps/test/scratch_test.py#L20)
```
  File "<string>", line 1
    C:\users
     ^
SyntaxError: invalid syntax
```
On Python 3, this is _not_ a syntax error.

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./build/fbcode_builder/getdeps/test/scratch_test.py:20:1: E999 SyntaxError: (unicode error) 'rawunicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX
                r"C:\users\alice\appdata\local\temp\fbcode_builder_getdeps",
^
1     E999 SyntaxError: (unicode error) 'rawunicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX
1
```

**Comment by snarkmaster** [comment]
Thanks, @cclauss — we'll get this fixed.

This isn't part of Bistro proper, but a shared "drop-in" called `fbcode_builder` that many FB projects use to build their open-source variants. So this Windows-specific test in no way affects Bistro, which only runs on Linux.

That said, I've reached out to the folks responsible for this file to get them to fix it.

I'll close it once it's fixed.

**Comment by snarkmaster** [comment]
Should be fixed now: https://github.com/facebook/bistro/commit/0a3f7b0073d4f42ba26ecb94d39b0fc7e0af71e0
