### ISSUE TITLE
Question: is this project dead?

### ISSUE THREAD

**Issue by alexef** [facebook/bistro#6]
There doesn't seem to be much activity over the past two years now.

**Comment by snarkmaster** [comment]
Thanks for asking! The inactivity on Github is more of a hibernation thing. A confluence of factors, some personal, some tooling-related, made it so that we did not push updates. That has now changed, so you should be seeing a stream of commits within the next few days.

**Comment by snarkmaster** [comment]
@alexef -- just wanted to let you know that I've pushed the last 1.5 years worth of activity up to Github, and revamped the build setup. For the build, take a look here:

https://github.com/facebook/bistro/tree/master/bistro/build/ci

Suggested reading:

```
less README
less fbcode_builder/README.docker
less build_steps.py
./make_docker_context.py --help
less travis_docker_build.sh
```

PS Ubuntu 14.04's build has a known missing `-y` in the `apt-get` instructions, but if you ran the `Dockerfile` manually that wouldn't be an issue. Will fix shortly.

**Comment by alexef** [comment]
Thank you :+1:
